# Generated by Django 4.1.1 on 2022-09-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FierstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('FatherName', models.CharField(max_length=30)),
                ('NationalCode', models.IntegerField(null=True)),
                ('Age', models.IntegerField(null=True)),
                ('PhoneNumber', models.IntegerField(null=True)),
                ('Adress', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null=True)),
                ('EnterDate', models.DateTimeField(auto_now_add=True)),
                ('Eghamat', models.IntegerField(null=True)),
                ('TypeRoom', models.CharField(choices=[('twins', 'تویین'), ('double', 'دوبل'), ('oneroom', 'تک اتاقه'), ('towroom', 'دو اتاقه')], max_length=10)),
                ('AgentName', models.CharField(choices=[('snaproom', 'اسنپ روم'), ('jabama', 'جاباما'), ('otaghak', ' اتاقک'), ('lamaso', 'لاماسو')], max_length=20)),
                ('Relatelastname1', models.CharField(default='null', max_length=20)),
                ('Relatename1', models.CharField(default='null', max_length=20)),
                ('Relatetype1', models.CharField(choices=[('family1', 'بستگان درجه1'), ('family2', 'بستگان درجه2'), ('freind', ' دوست'), ('coworker', 'همراه'), ('1', '1')], default='1', max_length=20, null=True)),
                ('Relatename2', models.CharField(default='null', max_length=20)),
                ('Relatelastname2', models.CharField(default='null', max_length=20)),
                ('Relatetype2', models.CharField(choices=[('family1', 'بستگان درجه1'), ('family2', 'بستگان درجه2'), ('freind', ' دوست'), ('coworker', 'همراه'), ('1', '1')], default='1', max_length=20, null=True)),
                ('Relatename3', models.CharField(default='null', max_length=20)),
                ('Relatelastname3', models.CharField(default='null', max_length=20)),
                ('Relatetype3', models.CharField(choices=[('family1', 'بستگان درجه1'), ('family2', 'بستگان درجه2'), ('freind', ' دوست'), ('coworker', 'همراه'), ('1', '1')], default='1', max_length=20, null=True)),
                ('UserGuest', models.ManyToManyField(to='hotel.users')),
            ],
        ),
    ]
